#!/bin/sh
# install.sh - put claude-mode's bin/* on your PATH.
#
# POSIX (macOS, Linux, WSL): symlinks bin/* into ~/.local/bin, so a git pull
# updates the installed command with no reinstall.
# Windows (Git Bash / MSYS2): Git Bash's `ln -s` silently copies instead of
# linking, and cmd.exe and PowerShell can't run a shebang script at all, so
# there we generate a pair of tiny launcher shims per script - a POSIX one for
# Git Bash and a .cmd one for cmd/PowerShell - both of which exec the script
# out of this repo. Same net effect: git pull is still the update path.
#
# Idempotent: safe to re-run. Never clobbers an existing profile.json.
set -eu

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    *)
      echo "install.sh: unknown argument '$arg'" >&2
      exit 1
      ;;
  esac
done

SELF="$(readlink -f "$0" 2>/dev/null || echo "$0")"
REPO_ROOT="$(cd "$(dirname "$SELF")" && pwd)"

_run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "+ $*"
  else
    "$@"
  fi
}

. "$REPO_ROOT/lib/python.sh"

PLATFORM="$("$PYTHON" "$REPO_ROOT/lib/platform.py")"

if [ "$PLATFORM" = "windows" ] && ! command -v cygpath >/dev/null 2>&1; then
  echo "install.sh: native Windows Python but no cygpath on PATH." >&2
  echo "  Run this from Git Bash or an MSYS2 shell, which ship cygpath." >&2
  exit 1
fi

# The Python side speaks native paths (C:\Users\me\...); this shell speaks
# POSIX (/c/Users/me/...). cygpath bridges the two on Windows and is a no-op
# everywhere else.
_to_posix() {
  if [ "$PLATFORM" = "windows" ]; then cygpath -u "$1"; else printf '%s\n' "$1"; fi
}

_to_native() {
  # -m yields a Windows path with forward slashes, which cmd.exe, python and
  # bash all accept and which needs no backslash escaping inside a shim.
  if [ "$PLATFORM" = "windows" ]; then cygpath -m "$1"; else printf '%s\n' "$1"; fi
}

INSTALL_DIR="$(_to_posix "$("$PYTHON" "$REPO_ROOT/lib/platform.py" --install-dir)")"
if [ -z "$INSTALL_DIR" ]; then
  echo "install.sh: lib/platform.py --install-dir returned nothing" >&2
  exit 1
fi

# Resolve HOME through lib/platform.py rather than $HOME: on Windows the two
# disagree, and profile.json has to land where claude-mode itself will read it.
HOME_DIR="$(_to_posix "$("$PYTHON" "$REPO_ROOT/lib/platform.py" --home)")"
if [ -z "$HOME_DIR" ]; then
  echo "install.sh: lib/platform.py --home returned nothing" >&2
  exit 1
fi

echo "install.sh: platform is $PLATFORM"
echo "install.sh: install dir is $INSTALL_DIR"

if [ "$DRY_RUN" -eq 1 ]; then
  echo "+ mkdir -p $INSTALL_DIR"
else
  mkdir -p "$INSTALL_DIR"
fi

REPO_ROOT_NATIVE="$(_to_native "$REPO_ROOT")"

# True if $1 is something a previous install.sh run put there (a symlink into
# this repo, or a shim referencing it) and is therefore ours to replace.
_ours() {
  if [ -L "$1" ]; then
    case "$(readlink -f "$1" 2>/dev/null || true)" in
      "$REPO_ROOT"/*) return 0 ;;
      *) return 1 ;;
    esac
  fi
  # Only Windows installs leave regular files behind, so only there can a
  # regular file be ours. Elsewhere a non-symlink at the destination is
  # somebody else's, exactly as before shims existed.
  [ "$PLATFORM" = "windows" ] || return 1
  grep -q "claude-mode-shim" "$1" 2>/dev/null &&
    grep -qF "$REPO_ROOT_NATIVE" "$1" 2>/dev/null
}

# Write the Windows launcher pair for one repo script.
_write_shims() {
  # $1 = repo script (POSIX path), $2 = dest basename
  _target="$(_to_native "$1")"
  case "$(head -n1 "$1")" in
    *python*) _runner="$PYTHON" ;;
    *) _runner="bash" ;;
  esac

  if [ "$DRY_RUN" -eq 1 ]; then
    echo "+ write shim $INSTALL_DIR/$2 ($_runner $_target)"
    echo "+ write shim $INSTALL_DIR/$2.cmd ($_runner $_target)"
    return 0
  fi

  {
    echo "#!/usr/bin/env bash"
    echo "# claude-mode-shim: generated by install.sh, edits here are lost on reinstall"
    echo "exec $_runner \"$_target\" \"\$@\""
  } > "$INSTALL_DIR/$2"
  chmod +x "$INSTALL_DIR/$2"

  {
    printf '@echo off\r\n'
    printf '@rem claude-mode-shim: generated by install.sh, edits here are lost on reinstall\r\n'
    printf '%s "%s" %%*\r\n' "$_runner" "$_target"
  } > "$INSTALL_DIR/$2.cmd"
}

# Clear every destination this script owns, or report why we can't. Returns
# non-zero (without deleting anything) if any of them belongs to someone else,
# so a half-replaced launcher pair is not a reachable state.
_claim_dests() {
  for _d in "$@"; do
    { [ -e "$_d" ] || [ -L "$_d" ]; } || continue
    if ! _ours "$_d"; then
      echo "install.sh: WARNING - $_d exists and was not created by install.sh, skipping" >&2
      echo "install.sh:   Move or delete it and re-run if you want install.sh to own it." >&2
      return 1
    fi
  done
  for _d in "$@"; do
    { [ -e "$_d" ] || [ -L "$_d" ]; } || continue
    _run rm -f "$_d"
  done
  return 0
}

for script in "$REPO_ROOT"/bin/*; do
  [ -f "$script" ] || continue
  name="$(basename "$script")"
  dest="$INSTALL_DIR/$name"

  if [ "$PLATFORM" = "windows" ]; then
    _claim_dests "$dest" "$dest.cmd" || continue
    _write_shims "$script" "$name"
    echo "install.sh: shimmed $dest (+ .cmd) -> $script"
  else
    _claim_dests "$dest" || continue
    _run ln -s "$script" "$dest"
    echo "install.sh: linked $dest -> $script"
  fi
done

# Profile resolution mirrors lib/profile.py: ~/.claude/claude-mode/ is the
# preferred location (beside the settings.json this tool manages), the XDG
# path is the legacy fallback. Never clobber an existing profile in EITHER.
CLAUDE_PROFILE="$HOME_DIR/.claude/claude-mode/profile.json"
XDG_PROFILE="${XDG_CONFIG_HOME:-$HOME_DIR/.config}/claude-mode/profile.json"

if [ -f "$CLAUDE_PROFILE" ]; then
  echo "install.sh: $CLAUDE_PROFILE already exists, leaving it alone"
elif [ -f "$XDG_PROFILE" ]; then
  echo "install.sh: $XDG_PROFILE already exists, leaving it alone"
else
  if [ -d "$HOME_DIR/.claude" ]; then
    PROFILE_DEST="$CLAUDE_PROFILE"
  else
    PROFILE_DEST="$XDG_PROFILE"
  fi
  CONFIG_DIR="$(dirname "$PROFILE_DEST")"
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "+ mkdir -p $CONFIG_DIR"
  else
    mkdir -p "$CONFIG_DIR"
  fi
  _run cp "$REPO_ROOT/profiles/example.json" "$PROFILE_DEST"
  echo "install.sh: wrote starter profile to $PROFILE_DEST"
  echo "install.sh: NOTE - that profile ships with placeholder values."
  echo "install.sh:   Edit it before running claude-mode (see 'Profile setup' in README.md)."
fi

# Ask Python whether the dir is on PATH: on Windows a shell-side string compare
# is worthless, because $PATH here is POSIX-form and the install dir is native.
if ! "$PYTHON" "$REPO_ROOT/lib/platform.py" --check-path >/dev/null 2>&1; then
  echo "install.sh: WARNING - $INSTALL_DIR is not on your \$PATH. Add it to your shell rc file." >&2
fi

echo "install.sh: done"
